# Generated by Django 4.1.13 on 2024-05-12 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=60,
                        unique=True,
                        verbose_name="enter ur contact email",
                    ),
                ),
                ("username", models.CharField(max_length=30, unique=True)),
                (
                    "medireg",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        verbose_name="enter ur medical identification number",
                    ),
                ),
                (
                    "clinic",
                    models.CharField(
                        max_length=30, verbose_name="enter ur clinic name"
                    ),
                ),
                (
                    "clinicreg",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        verbose_name="enter ur clinic registration number",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="datejoined"),
                ),
                ("status", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_doctor", models.BooleanField(default=False)),
                ("is_pharmacy", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bilid", models.IntegerField(default=71167, unique=True)),
                ("billtime", models.DateTimeField(auto_now_add=True)),
                (
                    "smsnumber",
                    models.CharField(blank=True, default=None, max_length=10),
                ),
                ("bilnote", models.TextField(blank=True, default=None, max_length=100)),
                (
                    "billdoc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Desies",
            fields=[
                (
                    "desiesid",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "desiesname",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="enter the disese name"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="medicine",
            fields=[
                (
                    "medineid",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "medename",
                    models.CharField(
                        max_length=30,
                        unique=True,
                        verbose_name="enter the medicine name",
                    ),
                ),
                ("adddate", models.DateTimeField(auto_now_add=True)),
                ("status", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="subdesies",
            fields=[
                (
                    "minidid",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("subdesiesna", models.CharField(default=None, max_length=45)),
                (
                    "maindesis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="docebill.desies",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="collection",
            fields=[
                (
                    "collid",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("days", models.PositiveIntegerField(blank=True)),
                ("note", models.CharField(blank=True, max_length=100)),
                ("status", models.BooleanField(default=False)),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="docebill.medicine",
                    ),
                ),
                (
                    "subdesies",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="docebill.subdesies",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="billphar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="docebill.bill"
                    ),
                ),
                (
                    "billedpharmacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "collid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="docebill.collection",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bill",
            name="collctionid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="docebill.collection",
            ),
        ),
    ]
