# Generated by Django 4.1.13 on 2024-05-13 06:37

from django.db import migrations, models
import docebill.models


class Migration(migrations.Migration):
    dependencies = [
        ("docebill", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="bilid",
            field=models.IntegerField(
                default=docebill.models.generate_unique_bilid, unique=True
            ),
        ),
    ]
