# Generated by Django 4.1.13 on 2024-04-28 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("docebill", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="bilid",
            field=models.IntegerField(default=91050, unique=True),
        ),
        migrations.AlterField(
            model_name="bill",
            name="billdoc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="docebill.medical"
            ),
        ),
        migrations.AlterField(
            model_name="billphar",
            name="billedpharmacy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="docebill.medical"
            ),
        ),
    ]
