# Generated by Django 4.1.13 on 2024-04-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docebill", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subdesies",
            name="subdesiesna",
            field=models.CharField(default=None, max_length=45),
        ),
        migrations.AlterField(
            model_name="bill",
            name="bilid",
            field=models.IntegerField(default=67233, unique=True),
        ),
    ]
