# Generated by Django 4.1.13 on 2024-04-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docebill", "0002_alter_bill_bilid_alter_bill_billdoc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="bilid",
            field=models.IntegerField(default=92838, unique=True),
        ),
    ]
