# Generated by Django 4.1.13 on 2024-04-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docebill", "0002_subdesies_subdesiesna_alter_bill_bilid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="bilid",
            field=models.IntegerField(default=45288, unique=True),
        ),
    ]
