# Generated by Django 4.1.13 on 2024-05-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docebill", "0002_alter_bill_bilid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="smsnumber",
            field=models.CharField(blank=True, default=None, max_length=12),
        ),
    ]
