# Generated by Django 4.1.13 on 2024-04-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docebill", "0003_alter_bill_bilid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="bilid",
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
