# Generated by Django 4.1.13 on 2024-04-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docebill", "0004_medical_groups_medical_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="bilid",
            field=models.IntegerField(default=12258, unique=True),
        ),
    ]
