# Generated by Django 4.1.13 on 2024-04-25 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authtoken", "0004_alter_tokenproxy_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("docebill", "0007_alter_bill_bilid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="bilid",
            field=models.IntegerField(default=86739, unique=True),
        ),
        migrations.CreateModel(
            name="PharmacyToken",
            fields=[
                (
                    "token_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="authtoken.token",
                    ),
                ),
                (
                    "pharmacy",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacy_auth_token",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("authtoken.token",),
        ),
        migrations.CreateModel(
            name="DoctorToken",
            fields=[
                (
                    "token_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="authtoken.token",
                    ),
                ),
                (
                    "doctor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_auth_token",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("authtoken.token",),
        ),
    ]
