# Generated by Django 4.1.13 on 2024-04-25 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("docebill", "0010_alter_bill_bilid_alter_doctortoken_doctor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="bilid",
            field=models.IntegerField(default=41571, unique=True),
        ),
        migrations.AlterField(
            model_name="doctortoken",
            name="doctor",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_auth_token",
                to="docebill.doctor",
            ),
        ),
        migrations.AlterField(
            model_name="pharmacytoken",
            name="pharmacy",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pharmacy_auth_token",
                to="docebill.pharmacy",
            ),
        ),
    ]
