# Generated by Django 4.1.13 on 2024-04-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docebill", "0011_alter_bill_bilid_alter_doctortoken_doctor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="bilid",
            field=models.IntegerField(default=50639, unique=True),
        ),
    ]
